### ISSUE TITLE
System.NotImplementedException: 'Function code 77 not supported.'

### ISSUE THREAD

**Issue by xuanhe168** [NModbus/NModbus#187]
code
```
using NModbus.Serial;
using System.IO.Ports;

using (SerialPort port = new SerialPort("COM3"))
{
    port.BaudRate = 9600;
    port.DataBits = 8;
    port.Parity = Parity.None;
    port.StopBits = StopBits.One;
    port.Open();

    var factory = new NModbus.ModbusFactory();
    var master = factory.CreateRtuMaster(port);

    while (true)
    {
        ushort[] registers = master.ReadHoldingRegisters(1, 1, 1);
        Console.WriteLine(string.Join(',', registers));

        await Task.Delay(TimeSpan.FromMicroseconds(600));
    }
}
```

exceptions
```
Function code 77 not supported.
   at NModbus.Extensions.ModbusFactoryExtensions.GetFunctionServiceOrThrow(IModbusFactory factory, Byte functionCode)
   at NModbus.IO.ModbusRtuTransport.ResponseBytesToRead(Byte[] frameStart)
   at NModbus.IO.ModbusRtuTransport.ReadResponse()
   at NModbus.IO.ModbusRtuTransport.ReadResponse[T]()
   at NModbus.IO.ModbusTransport.UnicastMessage[T](IModbusMessage message)
   at NModbus.Device.ModbusMaster.PerformReadRegisters(ReadHoldingInputRegistersRequest request)
   at NModbus.Device.ModbusMaster.ReadHoldingRegisters(Byte slaveAddress, UInt16 startAddress, UInt16 numberOfPoints)
   at Program.<<Main>$>d__0.MoveNext() in D:\Repositoryies\ObjectDetection-end-to-end\ModbusMasterConsole\Program.cs:line 17
```

**Comment by rquackenbush** [comment]
Thank you for your interest in the Modbus project! Unfortunately, serial support is still in progress for the latest major version of NModbus. 

In the short term, your best bet is to use the previous major version of the NModbus package.
